# -*- coding: utf-8 -*-
"""Apuntes de clase Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vk1dgiTUHAtZNrfEx-mqzba-rkNtVBje
"""

int(a) #funciones
a.upper() #metodos

a= "2.4"
dir(a)

numero = int(input("Ingrese un número "))
if numero % 2 == 0 and numero % 10 ==  0:
  print("El número es par y divisible por 10")
else:
  print("No cumple la condición")

calificación1 = float(input("Ingrese la calificación de los exámenes "))
calificación2 = float(input("Ingrese su cailificación en los proyectos "))
if calificación1 >= 60 and calificación2 >= 70:
  print("Aprobó")
else:
  print("Reprobó")

edad = int(input("Ingrese la edad"))
licencia = input("¿Tiene licencia vigente? Si/No").lower()
alcohol = input("¿Está bajo efectos del alcohol? Si//No").lower()

if (edad >= 18 and licencia == "si" and alcohol == "no"):
  print(("--"*5,"Puede conducir","--"*5))
elif (16 <= edad <= 17) and licencia == "si" and alcohol == "no":
  print("--"*5,"Puede conducir con acompañante","--"*5)
else:
  print("--"*5,"No puede conducir","--"*5)

lista_vacía = []
type(lista_vacía)

lista_num = [1,24.5,14,29]
print(lista_num)

lista_combinados = ["Medellín", "Camilo", 34, True]
print(lista_combinados)

"""**Acceso a los métodos de un tipo de variable**"""

a = 2
print(dir(a))

b = []
print(dir(b))

"""**Método append para listas**"""

lista_vacia = []
lista_vacia.append(12)
lista_vacia.append(36)
print(lista_vacia)

sum(lista_vacia)

len(lista_vacia)

min(lista_vacia)

#datos1 = ciudad, dato2= nombre, dato3=edad; dato4=trabaja?,dato5=estudia?
datos_camilo = ["Medellín","Camilo", 23, True, "Si"]
datos_ana = ["Bogota", "Ana", 22, False, "Si"]

camilo_trabaja = datos_camilo[3]
ana_estudia = datos_ana[4]

"""**Identación:** bloques de separación
**Indexación:** ubicar los datos en cierta posición

> Agregar bloque entrecomillado


"""



datos_camilo[0:1+1]

datos_ana[-3:]

nombres = [datos_camilo[1], datos_ana[1]]
print(nombres)

datos =  [datos_camilo[1:4], datos_ana[1:4]]
print(datos)

print(datos[0][2]) #acceder a la posición 0 de datos; luego posición 2 de datos_camilo que está dentro de la lista datos.
print(datos[1][2])

datos.append(["Camila", 20, True])

print(datos)

datos

datos_carlos = ["Santa Marta", "Carlos", 26, False, "si"]

datos[3]= datos_carlos
print(datos)

datos [3][2] = 27
print(datos)

"""**Ejercicio**"""

una_lista = [2,1,8,7,9,3,5]
print(una_lista)

una_lista.pop(5)
print(una_lista)

una_lista.append(0)
una_lista.append(1)
una_lista.append(3)
print(una_lista)

una_lista.sort()
print(una_lista)

max(una_lista)

min(una_lista)

sum(una_lista)

len(una_lista)

sum(una_lista)/len(una_lista)

una_lista.clear()
print(una_lista)

"""**Ciclo (para)**"""

for variable in range(5):
  print(variable)

edad1= int(input("Ingrese la edad 1"))
edad2= int(input("Ingrese la edad 2"))
edad3= int(input("Ingrese la edad 3"))
edad4= int(input("Ingrese la edad 4"))
edad5= int(input("Ingrese la edad 5"))
edad6= int(input("Ingrese la edad 6"))
edad7= int(input("Ingrese la edad 7"))
edad8= int(input("Ingrese la edad 8"))
edad9= int(input("Ingrese la edad 9"))
edad10= int(input("Ingrese la edad 10"))

promedio = (edad1+edad2+edad3+edad4+edad5+edad6+edad7+edad8+edad9+edad10)/10
print("El promedio de edades es:"), promedio

edades = [] #si se coloca dentro del ciclo, no se registran los datos.
for i in range(10):
  edad = int(input(f"Ingrese la edad {i+1} ")) #input o print f, puedo colocar variables dentro de las comillas.
  edades.append(edad)
promedio = sum(edades)/len(edades)
print("El promedio de edades es: ", promedio)

"""**Break:**
detiene la ejecución del ciclo, break + condición

**Range:** range(n) ----> empieza en 0, hasta n, con paso de 1
range(m,n) ----> inicia en m, hasta n, con paso de 1
range(m,n,s) ----> inicia en m, hasta n, con paso de s
"""

for j in range (2,5):
  print(j)

for z in range (1,10,2):
  print(z)

#____________Ejercicio2___________
num = float(input("Ingrese el número a calcular la tabla: "))
for i in range(1,11):
    print(f"{num} x {i} = {num*i}")

N = int(input("Ingrese un número mayor a 1 "))
numeros = []
for i in range(N):
 num = int(input(f"Ingrese el numero {i+1} "))
 if num > 5:
  numeros.append(num)
 else:
  print("No hay números mayores a 5")

mayor = max(numeros)
menor = min(numeros)
promedio = sum(numeros)/len(numeros)
print("El máximo es: ", mayor)
print("El mínimo es: ", menor)
print("El promedio es: ", promedio)

contraseña = "ABCD1234"
for i in range(5):
  contraseña_ingresada = input("Ingrese la contraseña: ")
  if contraseña_ingresada == "ABCD1234":
    print("La contraseña es correcta")
    break
  else:
    print("La contraseña es incorrecta, vuelva a intentar")

tupla_vacia = tuple()
print(type(tupla_vacia))

tupla_tuplas = (1,2,3,(4,(4,5,6)),(7,8,9),1)

print(tupla_tuplas[4][1])

tupla_tuplas = (1,2,3,(4,(4,5,6)),(7,8,9),1)

print(tupla_tuplas[3][1][1])

tupla_num = (1,2,3,3,3,4,4,3,5,3)
conteo_3 = tupla_num.count(3)
print(conteo_3)

tupla_enteros = (1,2,3)
tupla_caracteres = ("A","B","C")

tupla_suma = tupla_enteros + tupla_caracteres
print(f"La suma de la tupla es: {tupla_suma}")

tupla_multiplicacion = tupla_enteros * 3
print(f"La multiplicacion de una tupla da {tupla_multiplicacion}")

dias_semana = ("Lunes", "Martes", "Miercoles", "Jueves",
               "Viernes","Sabado", "Domingo")
for dias in dias_semana:
  print(dias)

tupla_coordenadas = ((1,2),(3,4),(4,5),(5,6))
for coordenada in tupla_coordenadas:
  print(f"Punto: {coordenada[0], coordenada[1]}")

tupla_estudiantes = (("Allison", 18, 5),("Luis", 22, 4),("Ana", 19, 3.0))
for i in range(len(tupla_estudiantes)):
  #print(tupla_estudiantes[i])
  if tupla_estudiantes[i][2] > 3.5:
    print(f"El estudiante {tupla_estudiantes[i][0]} tiene nota mayor a 3.5")

"""**Diccionarios**"""

diccionario_juli = {
    "nombre": "Juli",
    "edad": 23,
    "ciudad": "Medellín"
}
print(diccionario_juli)

diccionario_personas = {
    "Nombre": ["Juli", "Sandra", "Carlos", "Sofia"],
    "Edad" : [20, 21, 19, 24],
    "Ciudad" : ["Medellín", "Rionegro", "Bogota", "Amazonas"]
}
print(diccionario_personas)

print(diccionario_personas ["Ciudad"])

diccionario_personas["Profesion"] = ["Chef", "Arquitecta", "Abogado", "Ingeniera"]
print(diccionario_personas)

diccionario_personas["Nombre"][2] = "Laura"
print(diccionario_personas)

a = diccionario_personas.copy()
print(a)

print(diccionario_personas.keys())

for key, value in diccionario_personas.items():
  print(f"La llave es {key} y su valor {value}")

frase = input("Ingresa una frase")
frase_partes = frase.split()
diccionario = {}

for i  in frase_partes:
 diccionario[i] = frase_partes.count(i)
 print()

"""
**Funciones**


"""

def di_hola(nombre):
  print("Hola",nombre)

di_hola(nombre = "Juan")

def resta(a,b):
  c= a-b
  return c

resta(5,3)

def resta1(a,b,c = 0):
  return a-b+c, c-a-b

resultado1, resultado2 = resta1(1,2)
print("El resultado1 es:",resultado1)
print("El resultado2 es:",resultado2)

"""El return funciona como una especie de break en los ciclos, ejecuta los valores y se sale de la función, vuelve hasta antes de la función, todo lo que esté después no se ejecutará"""

def area_triangulo(base,altura):
  area = base*altura/2
  print("El area es :",area)
  #return area no es demandante, el print indica el resultado

area_triangulo(4,5)
area_triangulo(8,7)

def numero_mayor(n1,n2,n3):
  d = [n1,n2,n3]
  return max(d)

numero_mayor(55,-8,64.3)

lista = [1,2,3,4,5,6,7,8,9,10]
def pares(lista):
  num_pares = []
  for i in lista:
    if i%2 ==0:
      num_pares.append(i)
  return num_pares

lista_pares = pares(lista)
print("Los números pares son: ", lista_pares)

def factorial(N):
  num_fac = 1
  for i in range(1,N+1): #Al revés(N,1,-1)
    num_fac = num_fac * i
  return num_fac

factorial_num = factorial(5)
print(factorial_num)

"""**Control de versiones**

Git:
se genera un respositorio donde se almacenan y se admninistran todos los archivos de un proyecto
Local: en nuestro PC y no necesariamente compartido
Remotos: Se encuentran en repositorios "abiertos"

**LIBRERIAS**

***(Clase 17)***
Limitaciones de manejo de datos numéricos en python nativo:
Lento para cálculos númericos grandes.
Falta de operaciones vectorizadas.
"""

import time
lista= list(range(100000))
inicio = time.time()
[valor * 2 for valor in lista]

print("Tiempo de ejecución con listas: ", time.time()-inicio)

import numpy as np
arreglo = np.arange(100000)
inicio = time.time()
arreglo * 2
print("Timpo de ejecución con listas: " , time.time()-inicio)

"""arreglo = arrays
np.array

"""

import numpy as np
arreglo = np.array([1,2,3])
print(arreglo)

print("El número de dimensiones del arreglo es: ", arreglo.ndim)
print("La forma del arreglo es: ", arreglo.shape)
print("El número total de elementos es: ", arreglo.size)
print("Los tipos de datos en el arreglo son: ", arreglo.dtype)

arreglo_2d = np.array([[1,2,3],[4,5,6]])
print(arreglo_2d)

arreglo_3d = np.array([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]]])

"""Indexación avanzada de arreglos, brigadas, .array, numpy

**Aritmética y operadores con arreglos**
"""

import numpy as np

matriz_1 = np.array ([[1,2,3],
                      [4,0,-5],
                      [-6,-7,-8]])

"""Se aplica operación para todos los elementos de la matriz"""

matriz_1 + 100

"""La operación solo se aplicará al tercer elemento."""

matriz_1[2,:]*3

3 / matriz_1

matriz_1 / 2

"""Operadores Lógicos"""

matriz_1 > 1

"""Se crean otras dos matrices matriz_2 y matriz_3, las cuales se utilizarán junto al matriz_1 con operadores lógicos"""

matriz_1.shape

matriz_2 = np.array([1,2,3])

matriz_2.shape

matriz_1 * matriz_2

matriz_3 = np.array ([[2],[4], [6]])

"""Arreglo compuesto de tres filas y una sola columna: (dos dimensiones)"""

matriz_3

matriz_3.shape

"""Matrices con dimensiones idénticas:

**ojo:** LAS OPERACIONES NO son como las realizadas en Algebra Lineal, para esto python tiene otras funciones diferentes.

FUNCIONES:
.reshape()
"""

import numpy as np
arreglo_2 = np.array([[1,2,3,4],
                      [5,6,7,8],
                      [9,10,11,12]])   #se sabe que está en 2 dimensiones porque hay dos corchetes abiertos para cosa diferentes

arreglo_2.shape

#reshape cambia la dimensión del arreglo
arreglo_2.reshape(3,2,2) #se debe dar la forma con la misma cantidad de elementos

arreglo_2.reshape(12)

np.resize(arreglo_2, (3,3,2)) #permite agregar más elementos de los que ya hay, pero las llenará con ceros

"""Matriz transpuesta"""

matriz_2.transpose()

matriz_T =  np.transpose(matriz_2)

matriz_T

"""np.squeeze elimina una dimensión del arreglo

"""

import numpy as np
origen = np.arange(9).reshape(3,3,1)

origen

np.squeeze(origen,2) #arreglo, dimensión

"""np.concatenate() el más recomendado
arreglo
"""

arreglo_1 = np.array ([[1,2],
                       [3,4]])

arreglo_2 = np.array ([[5,6],
                       [7,8]])

np.concatenate((arreglo_1,arreglo_2), axis = 1)

#concatenar en eje 0 filas
np.concatenate((arreglo_1,arreglo_2),0)

"""¿De que depende el axis(eje)? De la necesidad que yo tenga, identificar si debo pegarlos desde las filas o desde las columnas"""

arreglo_original =  np.arange(9).reshape(3,3)

arreglo_original

arreglo_eje_0 = np.array([[5,6,7], [8,9,10]])

arreglo_eje_0

#eje= 0 para filas y eje=1 para columnas

np.append(arreglo_original, arreglo_eje_0, axis=0) #filas = 0 #si yo intento hacerlo desde columnas, como no tienen el mismo número de filas, va a salir un error, por eso hay que elegir bien el axis

"""**librería PANDAS**"""

import numpy as np
matriz = np.arange(9)
print(matriz)

diccionario = {'Curso 1': [10, 5, 33, 45, 25, 22],
               'Curso 2': [10, 5, 33, 45, 25, 22],
               'Curso 3': [10, 5, 33, 45, 25, 22],
               'Curso 4': [10, 5, 33, 45, 25, 22]}

import pandas as pd
pd.DataFrame(data = diccionario)

"""*   Las columnas de un dataframe de Pandas son objetos instanciados pd.Series o simplemente "Series"

*   La siguiente celda regresará los renglones del objeto cursos correspondientes a los índices 'enero' , 'marzo' y 'mayo' usando la sintaxis cursos[::2]. Tomelos valores haciendo saltos de 2.
"""

cursos[::2]

import pandas as pd
import numpy as np
from datetime import datetime

datos = pd.DataFrame(np.arange(20).reshape(5,4),
             columns=('primero','segundo','tercero','cuarto'))

indice_1 = ("Lunes","Martes","Miércoles")
marco_1 = pd.DataFrame({'Centro':
                        [1520,1640,1043],
                        'Sur':[1422,1673,1534],
                        'Oriente':[1021,1073,1100]},
                       index=indice_1)

indice_2 = ("Jueves","Viernes","Sábado")
marco_2 = pd.DataFrame({'Centro':
                        [1321,1459,1875],
                        'Sur':[1622,1841,1920],
                        'Oriente':[1500,1432,1491]},
                       index=indice_2)

indice = ['gerente','supervisor','vendedor','cajero']
personal = pd.DataFrame ({'nombres':('Juan Perez',
                                     'María Sánchez',
                                     'Jorge Vargas',
                                     'Rodrigo Martínez'),
                          'fechas':(datetime(1995,12,21),
                                    datetime(1989,1,13),
                                    datetime(1992,9,14),
                                    datetime(1993,7,8)),
                          'saldo':(2500,
                                   5345,
                                   np.nan,
                                   11323.2),
                          'al corriente':(True,
                                          True,
                                          False,
                                          True)}, index=indice)