# -*- coding: utf-8 -*-
"""ContinuaciónPandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Stmv7tOgIn9oWX7aLEigJ8XVlp_afnBQ
"""

import pandas as pd

from datetime import datetime

facturas = pd.DataFrame({'folio':(15234,

                      15235,

                      15236,

                      15237,

                      15238,

                      15239,

                      15240,

                      15241,

                      15242),

             'sucursal':('CDMX01',

                         'MTY01',

                         'CDMX02',

                         'CDMX02',

                         'MTY01',

                         'GDL01',

                         'CDMX02',

                         'MTY01',

                         'GDL01'),

             'monto':(1420.00,

                     1532.00,

                     890.00,

                     1300.00,

                     3121.47,

                     1100.5,

                     12230,

                     230.85,

                     1569),

             'fecha':(datetime(2019,3,11,17,24),

                     datetime(2019,3,24,14,46),

                     datetime(2019,3,25,17,58),

                     datetime(2019,3,27,13,11),

                     datetime(2019,3,31,10,25),

                     datetime(2019,4,1,18,32),

                     datetime(2019,4,3,11,43),

                     datetime(2019,4,4,16,55),

                     datetime(2019,4,5,12,59)),

            'cliente':(19234,

                       19232,

                       19235,

                       19233,

                       19236,

                       19237,

                       19232,

                       19233,

                       19232)

                        })

gastos_por_cliente = facturas.filter(items=["monto","cliente"])

gastos_por_cliente

clientes = gastos_por_cliente.groupby("cliente")

"""Se almacena en un objeto, agrupando por cliente"""

clientes

print(clientes.groups) #diccionario

for nombre_cliente, grupo in clientes:

clientes.size()

clientes.mean() #promedio

clientes.max()

clientes.min()

"""**Limpieza y datos faltantes:**"""

import pandas as pd
import numpy as np

"""Dataframe ilustrativo"""

poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,np.nan,None,2,4,2,14,5),
'Norte_II':(23,4,25,21,9,121,1,2),
'Centro_I':(15,23,2,120,40,121,0,5),
'Sur_I':(28,46,14,156,79,12,2,np.nan)}).set_index('Animal')

"""En muchos casos, los dataframes incluyen objetos de tipo np.nan. Por lo general este tipo de datos denota datos incompletos cuyo verdadero valor es desconocido."""

poblacion

#método isna
poblacion.isna()

poblacion.isna().sum()

#metodo isnull() ver si contienen Nan o es nulo
poblacion.isnull()

#metodo notna() igual que isna() pero negado, es decir en vez de true, es con false los que sean nan
poblacion.notna()

poblacion.notna().sum()

poblacion.shape

#metodo notnull() es igual a isnull(), pero con False, hace falta contar los datos faltantes
poblacion.notnull()

poblacion.notnull().sum()

#metodo fillna() es útil para sustituir los valores NaN por un valor que yo le de
#Lo más pertinente es reemplazar por el valor de la moda
poblacion.fillna(0)

poblacion.fillna("Inválido")

#metodo dropna() cuando es una cantidad de datos bastante extensa, no tiene mucho sentido sustituir, porque no influye mucho en todos los datos
poblacion.dropna()
#notar que la fila COYOTE y PUMA ya no están

poblacion1 = poblacion["Norte_I"].dropna() #Si pongo Norte_1 le estoy especificando al dropna que no me elimine el Puma
poblacion1

promedio = int(sum(poblacion1)/len(poblacion1))
poblacion["Norte_I"].fillna(promedio)
#Aqui reemplazamos los valores NaN por el promedio de datos de la columna

poblacion.duplicated()

otra_poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,4,None,2,4,2,14,4),
'Norte_II':(23,4,25,21,9,121,1,4),
'Centro_I':(15,4,2,120,40,121,0,4),
'Sur_I':(28,4,14,156,79,12,2,4)}).set_index('Animal')

otra_poblacion

otra_poblacion.duplicated()

otra_poblacion.drop_duplicates()

poblacion.head()

poblacion.tail() #5 últimos datos

#metodo isin() me dice si los valores que necesito si esta en el dataframe
poblacion.isin(range(20,31)).sum()

#Parámetro inplace. en lugar de insertar un nuevo dataframe, se reflejan los cambios en el original
poblacion #original

#para eliminar definitivamente
poblacion.inplace(nplace = True)

poblacion.replace(np.nan, 0) #reemplaza cualquier tipo de dato, no solo los NaN

poblacion.replace([0, np.nan], 'extinto')

poblacion.drop(['Centro_I'], axis=1, inplace = True)

poblacion

"""pd.read_csv()  """