# -*- coding: utf-8 -*-
"""Matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIBJDnOA7srDAqtwyaYj4LtCWSYgLpFC

**Librería matplotlib:**
"""

import matplotlib.pyplot as plt

x= [1,2,3,4,5]
y= [1,4,9,16,25]

plt.plot(x,y) #Gráfica más sencilla
plt.title("Gráfico de Líneas Básico") #Título del gráfico
plt.xlabel("Eje X") #Nombre Eje X
plt.ylabel("Eje Y") #Nombre Eje Y

plt.plot(y,x)

"""**Gráfico de barras**"""

categorias= ['A','B','C','D']
valores = [3, 7, 2, 5]

plt.bar(categorias,valores) #Gráfico de Barras

plt.title("Gráfico de barras")
plt.xlabel("Puntos de venta")
plt.ylabel("Ventas")
plt.show()

plt.figure() #Para que no se superpongan gráficas entre sí

x = [1,2,3,4,5]
y =

etiquetas = ['A', 'B', 'C', 'D']
sizes = [15, 30, 45, 10]

plt.pie(sizes, labels=etiquetas, autopct= '%1.1f%%',startangle= 90)
plt.title("Gráfico de pastel")
plt.show()

data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5]

plt.hist(data,bins=5, edgecolor='black') #edgecolor es opcional

plt.title("Histograma")
plt.xlabel("Valor")
plt.ylabel("Frecuencia")
plt.show()

"""**Subplots:**

"""

x = [1,2,3,4,5]
y = [1, 4, 9, 16, 25]

plt.subplot(2,2,1) #1 fila, 2 columnas, grafico 1
plt.plot(x,y)
plt.title("Gráfico de Líneas")

plt.subplot(2,2,2) #1 fila, 2 columnas, grafico 2
plt.bar(x,y)
plt.title("Gráfico de Barras")

plt.subplot(2,2,3) #1 fila, 2 columnas, grafico 3
plt.plot(x,y)
plt.title("Gráfico de Líneas")

plt.tight_layout() #Ajusta el espacio entre los subgráficos

"""**Gráficos personalizados**"""

x = [1,2,3,4,5]
y = [1, 4, 9, 16, 25]

y1 = [1,8,27,64,125]

plt.plot(x, y, color='green', linestyle = '--',marker='o',markersize=10, label="Crecimiento cuadrático")
plt.plot(x, y1, color='blue', linestyle = ':',marker='<',markersize=5, label="Crecimiento cúbico")

plt.title("Gráfico Personalizado")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()# mostrar las etiquetas (labels)
plt.show()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

file_path = r"/content/drive/MyDrive/Algoritmia Y Programación/kc_house_data.csv"
data = pd.read_csv(file_path)
data

data.info()

data.describe()

print(data.isna().sum()) #conteo por columna de datos NaN

print(data.duplicated().sum())

data['price'] < 0

data[data['price'] < 0]

data[data['bedrooms'] < 0 ]

data = data[data['bedrooms'] < 12]

data.columns

data.drop(["zipcode","lat","long"], axis=1,inplace=True)

data.columns

data.shape

data['house_age'] = 2026 - data['yr_built']

data["house_age"]

data['renovated_flag'] = data['yr_renovated'].apply(lambda x: 1 if x > 0 else 0)

data['renovated_flag']

sum(data["renovated_flag"] ==0)

sum(data["renovated_flag"] ==1)

data[(data['bedrooms']==3)&(data['floors']>=2)]

import matplotlib.pyplot as plt

df_line = data.groupby('bedrooms')['price'].mean()
plt.figure(figsize=(8,5))
plt.plot(df_line.index, df_line.values)
plt.title("Precio promedio según número de habitaciones")
plt.xlabel("Número de habitaciones")
plt.ylabel("Precio promedio")
plt.tight_layout()
plt.show()

"""Cantidad de habitaciones:"""

plt.figure(figsize=(8,5))
data['bedrooms'].value_counts().plot(kind='bar')
plt.title("Distribución de número de habitaciones")
plt.xlabel("Habitaciones")
plt.ylabel("Cantidad de viviendas")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
plt.hist(data['price'], bins=50)
plt.title("Histograma de precios de vivienda")
plt.xlabel("Precio")
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(data['sqft_living'], data['price'], s=10, alpha=0.3)
plt.title("Precio vs Área habitable")
plt.xlabel("sqft living")
plt.ylabel("Precio")
plt.tight_layout()
plt.show()

renov = data["renovated_flag"].value_counts()
etiquetas = ["No renovada", "Renovada"]
renov.index = etiquetas

plt.figure(figsize=(6,6))
plt.pie(renov.values, labels=renov.index, autopct='%1.1f%%')
plt.title("Porcentaje de casas renovadas")
plt.tight_layout()
plt.show()

import seaborn as sb